//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGateWay
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelsAction
    {
        public long Id { get; set; }
        public string LabelSerialId { get; set; }
        public string BatteryVoltage { get; set; }
        public string BatterLevel { get; set; }
        public string SsId { get; set; }
        public string WifiPassword { get; set; }
        public string Interval { get; set; }
        public string Variable1 { get; set; }
        public string Variable2 { get; set; }
        public string Variable3 { get; set; }
        public string HttpPostLink { get; set; }
        public Nullable<System.DateTime> CreDate { get; set; }
        public string ClvUserName { get; set; }
        public string ClvPassword { get; set; }
        public string Networks { get; set; }
        public string GeoRequestData { get; set; }
    }
}
